production.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include `production.h`
#include <math.h>
#include <string.h>
Functions
bool production (int argc, char *argv[])
void PlayOne (unsigned int nr, unsigned int nc, char *Old, char *New)
void usage (void)
char getLetter (int row, int col, int nCols, char *Old)
int HowManyNeighbors (int row, int col, int nRows, int nCols, char *Old)
void readFileIntoArray (int nRows, int nCols, int howManyLinesInFile, int maximumWidth, char *ar_p, FILE *fp)
int generate (int gens, int nRows, int nCols, char *old_p, char *new_p, char *other_p, char print, char pause)
bool anyX (char *arr, int nRows, int nCols)
bool sameContent (char *one_p, char *another_p, int nRows, int nCols)
void printThis (int nRows, int nCols, char *old_p)
Function Documentation
anyX()
bool anyX (char * arr, int nRows, int nCols)
anyX checks whether the given array contains an x or not
Parameters
char* arr, the array to be checked
int nRows, the number of rows in the array
int nCols, the number of Columns in the array
Returns
bool any, true/false if an x is present
Referenced by generate(), and testAnyX().
generate()
int generate (int gens, int nRows, int nCols, char * old_p, char * new_p, char * other_p, char print, char pause)
generate is the function that process a generation(s) under the rules of the game of life
Parameters
int gens, the amount of generations to run
int nRows, the amount of rows in the array
int nCols, the amount of columns in the array
char* old_p, the array of the previous generation
char* new_p, the array of the next/current generation
char* other_p, the place holder array to swap pointers
char print, y/n for whether or not the generations should be printed
char pause, y/n for whether or not the program should pause between generations
Returns
int g, the amount of successful generations
References anyX(), PlayOne(), printThis(), and sameContent().
Referenced by production(), testBlinker(), and testGlider().
getLetter()
char getLetter (int row, int col, int nCols, char * Old)
getLetter gets the specific letter at given row/column of the old array in a generation
Parameters
int row, the row of the letter
int col, the column of the letter
int nCols, the amount of Columns in the array
char* Old, the array for the generation
Returns
char result, the letter at the given row/column of the old array
Referenced by HowManyNeighbors(), and PlayOne().
HowManyNeighbors()
int HowManyNeighbors (int row, int col, int nRows, int nCols, char * Old)
HowManyNeighbors is a helper function for calculating the number of neighbors for each cell
Parameters
int row, the row of the cell
int col, the column of the cell
int nRows, the number of rows in the array
int nCols, the number of columns in the array
char* Old, the array for the function to search through
Returns
int result, the amount of neighbors for the given cell
References getLetter().
Referenced by PlayOne(), and testCountNeighbors().
PlayOne()
void PlayOne (unsigned int nr, unsigned int nc, char * Old, char * New)
PlayOne carries out one generation
Parameters
unsigned int nr, the number of rows in the petri dish
unsigned int nc, the number of columns in the petri dish
char* Old, the location of the upper left of starting petri dish
char* New, the location of the upper left of the ending petri dish
Returns
There is none, because results are in New array
References getLetter(), and HowManyNeighbors().
Referenced by generate(), and testPlayOne().
printThis()
void printThis (int nRows, int nCols, char * old_p)
printThis prints out the given array
Parameters
int nRows, the number of rows for the given array
int nCols, the number of columns for the given array
char* old_p, the array to be printed
Returns
There is nothing to be returned, the function is of type void
Referenced by generate(), and production().
production()
bool production (int argc, char * argv[])
References generate(), printThis(), readFileIntoArray(), and usage().
Referenced by main().
readFileIntoArray()
void readFileIntoArray (int nRows, int nCols, int howManyLinesInFile, int maximumWidth, char * ar_p, FILE * fp)
readFileIntoArray transfers the Game Of Life state from a given file into an array using pointers
Parameters
int nRows, the number of rows for the given array
int nCols, the number of colunms for the given array
int howManyLinesInFile, the number of lines from the Game State file
int maximumWidth, the finite number of width for the game
char* ar_p, the array to be filled
FILE* fp, the file to be read
Returns
There is nothing to return, the function is void
Referenced by production(), testBlinker(), and testGlider().
sameContent()
bool sameContent (char * one_p, char * another_p, int nRows, int nCols)
sameContent is a helper function that checks to see if the contents of each given array is the same
Parameters
char* one_p, the first array for comparison
char* another_p, the second array for comparison
int nRows, the number of rows for the two arrays (assuming they are the same)
int nCols, the number of columns for the two arrays (assuming they are the same)
Returns
bool same, true/false if the content of both arrays are the same
Referenced by generate(), and testSameContent().
usage()
void usage (void)
Usage notifies the user of them of the correct command line input for the Game Of Life Program to work
Returns
print statement with correct format
Referenced by production().