mystruct.h File Reference
#include <stdlib.h>
Data Structures
struct Employee
Macros
#define MAX_NAME (99)
Functions
struct Employee * makeEmployee (int birth, int start, const char *name)
void printEmployee (struct Employee *e)
char * randString (void)
int randYear (void)
struct Employee * makeRandomEmployee (void)
struct Employee ** makeRandomEmployees (size_t count)
void freeEmployees (struct Employee **e, size_t number)
void printEmployees (struct Employee **e, size_t number)
struct Employee ** shallowCopy (struct Employee **e, size_t number)
struct Employee * copyEmployee (struct Employee *e)
struct Employee ** deepCopy (struct Employee **e, size_t number)
Macro Definition Documentation
MAX_NAME
#define MAX_NAME (99)
mystruct.h
Author
Mike Ciaraldi Sample structs
Function Documentation
copyEmployee()
struct Employee* copyEmployee (struct Employee * e)
Copy an employee structure
Parameters
e Employee to copy
Returns
A pointer to a duplicate, but different employee from the one passed in.
References Employee::birth_year, makeEmployee(), Employee::name, and Employee::start_year.
Referenced by deepCopy().
deepCopy()
struct Employee** deepCopy (struct Employee ** e, size_t n)
Creates a deep copy of an employee array. A deep copy of an employee array is a new array of employee pointers to new Employee structures that contain the same values for their birth year, start year and name as the original array.
Parameters
e Employee array to copy
n Length of employee array
Returns
deep copy of employee array
References copyEmployee().
Referenced by testDeepCopy().
freeEmployees()
void freeEmployees (struct Employee ** e, size_t n)
Free an array of employees
Parameters
e Employee array
n Length of employee array
Referenced by testFreeEmployees().
makeEmployee()
struct Employee* makeEmployee (int birth, int start, const char * name)
mystruct.c
Author
Mike Ciaraldi Allocates an Employee struct and fills in its fields
Parameters
birth Year the employee was born.
start Year the employee started with the company.
name String containing employee's name
Returns
Pointer to Employee struct, newly allocated from the heap.
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by copyEmployee(), makeRandomEmployee(), testMakeEmployee(), testRandString(), and testRandYear().
makeRandomEmployee()
struct Employee* makeRandomEmployee (void)
Makes a random employee
Returns
Pointer to employee structure.
References makeEmployee(), randString(), and randYear().
Referenced by makeRandomEmployees(), and testMakeRandomEmployee().
makeRandomEmployees()
struct Employee** makeRandomEmployees (size_t count)
Make an array of random employees defined by a given size parameter, count.
Parameters
count The number of employees to make
Returns
The pointer to the first element of the array of created random employees
References makeRandomEmployee().
Referenced by testDeepCopy(), testFreeEmployees(), testMakeRandomEmployees(), testPrintEmployees(), and testShallowCopy().
printEmployee()
void printEmployee (struct Employee * e)
Prints the information of the given employee object; their birth year, starting year and name
Parameters
struct Employee *e, the employee whose information is to be printed to the console
Returns
void
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by printEmployees(), testMakeEmployee(), testMakeRandomEmployee(), testMakeRandomEmployees(), testPrintEmployee(), testRandString(), and testRandYear().
printEmployees()
void printEmployees (struct Employee ** e, size_t n)
Print an employee array
Parameters
e Employee array
n Length of employee array
References printEmployee().
Referenced by testDeepCopy(), testPrintEmployees(), and testShallowCopy().
randString()
char* randString (void)
Creates a `first name` and ` last name` of 10 random lowercase letters separated by a space, the last of which is terminated by a null-terminator.
Returns
22 character array as defined by the function description
Referenced by makeRandomEmployee(), testRandString(), and testRandYear().
randYear()
int randYear (void)
Create an integer year between 1940 and 1999
Returns
an integer between 1940 and 1999
Referenced by makeRandomEmployee(), testRandString(), and testRandYear().
shallowCopy()
struct Employee** shallowCopy (struct Employee ** e, size_t n)
Creates a shallow copy of an employee array. A Shallow copy of an employee array is a new array of employee pointers that uses the same pointers from the original array. There is no structure duplication.
Parameters
e Employee array
number Length of employee array
Returns
shallow copy of employee array
Referenced by testShallowCopy().