tests.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include `tests.h`
#include `production.h`
#include `mystruct.h`
Macros
#define MAX_NAME (99)
Functions
bool tests (void)
bool testPrintEmployee ()
bool testMakeEmployee ()
bool testRandString ()
bool testRandYear ()
bool testMakeRandomEmployee ()
bool testMakeRandomEmployees ()
bool testPrintEmployees ()
bool testShallowCopy ()
bool testFreeEmployees ()
bool testDeepCopy ()
Macro Definition Documentation
MAX_NAME
#define MAX_NAME (99)
Referenced by testPrintEmployee().
Function Documentation
testDeepCopy()
bool testDeepCopy (void)
Tests the function deepCopy() by creating an array of 4 random employees and calling the function on it, compares all parts of the employee structure
Returns
true. return true if all parts of the employee structure from the original and copy are the same
References Employee::birth_year, deepCopy(), makeRandomEmployees(), Employee::name, printEmployees(), and Employee::start_year.
Referenced by tests().
testFreeEmployees()
bool testFreeEmployees (void)
Test the function freeEmployees() by creating an array of 4 random employees and calling the function on it
Returns
true. returns true if the function call works without errors
References freeEmployees(), and makeRandomEmployees().
Referenced by tests().
testMakeEmployee()
bool testMakeEmployee (void)
Tests the make Employee() function by making an employee with known data and printing it.
Returns
true. The only way to tell if it succeeds is to look at the output.
References makeEmployee(), and printEmployee().
Referenced by tests().
testMakeRandomEmployee()
bool testMakeRandomEmployee (void)
Tests the function makeRandomEmployee() by creating an employee using the function the outputting it to the console. Also tests the function by having it create an array of 4 random employees.
Returns
true. The only way to tell if it worked is by looking at the output.
References makeRandomEmployee(), and printEmployee().
Referenced by tests().
testMakeRandomEmployees()
bool testMakeRandomEmployees (void)
Tests the function makeRandomEmployees() by having it create an array of 4 random employees.
Returns
true. The only way to tell if it worked is by looking at the output.
References makeRandomEmployees(), and printEmployee().
Referenced by tests().
testPrintEmployee()
bool testPrintEmployee (void)
Test the printEmployee() function by creating a known structure and printing it.
Returns
true. The only way to tell if it succeeds is to look at the output.
References Employee::birth_year, MAX_NAME, Employee::name, printEmployee(), and Employee::start_year.
Referenced by tests().
testPrintEmployees()
bool testPrintEmployees (void)
Tests the function printEmployees() by having it print an array of 4 random employees.
Returns
true. The only way to tell if it worked is by looking at the output.
References makeRandomEmployees(), and printEmployees().
Referenced by tests().
testRandString()
bool testRandString (void)
Tests the randString() function by printing out a random string ,that is only printable characters, produced by the function.
Returns
true. The only way to tell if it succeeds is to look at the output for the employee that is made.
References makeEmployee(), Employee::name, printEmployee(), randString(), and randYear().
Referenced by tests().
testRandYear()
bool testRandYear (void)
Tests the randYear() function by printing out a random year between 1940 and 1999.
Returns
result. Returns true only if the year is between 1940 and 1999, can tell if it worked also by looking at output of created employee.
References makeEmployee(), Employee::name, printEmployee(), randString(), and randYear().
Referenced by tests().
tests()
bool tests (void)
References testDeepCopy(), testFreeEmployees(), testMakeEmployee(), testMakeRandomEmployee(), testMakeRandomEmployees(), testPrintEmployee(), testPrintEmployees(), testRandString(), testRandYear(), and testShallowCopy().
Referenced by main().
testShallowCopy()
bool testShallowCopy (void)
Tests the function shallowCopy() by creating an array of 4 random employees and comparing to original to the copy
Returns
true. only returns true if the two arrays are the same.
References makeRandomEmployees(), printEmployees(), and shallowCopy().
Referenced by tests().